### ISSUE TITLE
sink point for advice(Semantic Analysis)

### ISSUE THREAD

**Issue by 18Song** [SlaterLatiao/RevBugBench#13]
Sorry to bother you again. The sink point mentioned here refers to the location in the code where the vulnerability is triggered. 
Since fixreverter only injects CWE-476(then the sink point format must have been filtered), I would like to add CWE-119 and CWE-369, and I have summarized the sink point format of CWE-119 and CWE-369. 
But I can't find the code to filter the sink point format in phasar_plugin, so I would like to ask for your help.
![image](https://user-images.githubusercontent.com/73453430/233323148-5c5698a4-330a-4df3-8bed-33cc57e754c7.png)

**Comment by SlaterLatiao** [comment]
Hi, the FlowFunctions folder contains how the taint flows and how the sinks are defined. The code of `phasar_plugin` may be a little messy right now, and we do have plans to improve the code quality in general. Please feel free to ask if any part is unclear, and you are very welcome to share your improvements and extensions.

**Comment by 18Song** [comment]
> Hi, the FlowFunctions folder contains how the taint flows and how the sinks are defined. The code of `phasar_plugin` may be a little messy right now, and we do have plans to improve the code quality in general. Please feel free to ask if any part is unclear, and you are very welcome to share your improvements and extensions.

Some examples of sinks mentioned in the paper are reading/writing a tracked pointer, offsetting a pointer using a tracked number, and calling a library function where the tracked parameter is dereferenced, etc. I can understand this, but unfortunately, I still can't understand the logic when it comes to the code implementation.
such as 
![image](https://user-images.githubusercontent.com/73453430/234202738-c83b3203-08ae-4df0-b82d-f231e797e36e.png)
and this
![image](https://user-images.githubusercontent.com/73453430/234202890-ee2e817f-9c92-4fa5-b6e0-d18effbae354.png)
Could you explain the specific logic for implementing the sink point judgment?

**Comment by SlaterLatiao** [comment]
The general idea of the sink detection is that when a tainted value is dereferenced, it's a potential crash site for a injected bug. The semantic analyzer is implemented based on the phasar IFDSTaintAnalysis framework, and the implementations you quoted are defining the flow functions. We define the definition of tracing variables as the taint sources and use the flow functions to propagate data flow. The `GlobalData->Leaks` is a global data holder that saves all the potential dereferences of tainted values, and the `GlobalData->TaintPaths` records how the data propagates. In the end of analysis we trace from `GlobalData->Leaks` backward on the  `GlobalData->TaintPaths`, in order to decide which sources have data dependency to potential dereferences.
